### ISSUE TITLE
Pattern Wrangler Settings Error

### ISSUE THREAD

**Issue by nguyenquanghoang** [DLXPlugins/pattern-wrangler#32]
Pattern Wrangler Settings error when using Vietnamese translation for Pattern Wrangler.

![Pattern Wrangler](https://github.com/user-attachments/assets/8282c4bb-3524-495a-9de6-c05f5eab956b)

I have completed the Vietnamese translation for Pattern Wrangler. But unfortunately when using Vietnamese, the "Settings" section has an error and does not display the options

**Comment by ronalfy** [comment]
@nguyenquanghoang this should be fixed in version `1.1.1`.

**Comment by nguyenquanghoang** [comment]
> @nguyenquanghoang this should be fixed in version `1.1.1`.

@ronalfy Thank you very much, In addition, the new update shows "Vietnamese is not displayed in the settings" has reported an error at #33

**Comment by ronalfy** [comment]
Can you attach uour translation?

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error, please notify Ronald Huereca at
***@***.***

You can only delay the inevitable.
www.ronalfy.com

**Comment by nguyenquanghoang** [comment]
Problem: Pattern Wrangler with 120 Strings on WP .org but when synced to the website only has 38 Strings. So it will not display Vietnamese in the settings

Please visit the link https://translate.wordpress.org/locale/vi/default/wp-plugins/pattern-wrangler/ and export the translation because I can't see your email to send

PS: It seems your error is similar to Blocksy's that I encountered, which is the confusion between JSON files and MO/PHP

![Blocksy - Lỗi bản dịch đủ nhưng nhiều vị trí vẫn hiển thị tiếng anh](https://github.com/user-attachments/assets/1551825d-5a12-40ec-afc3-a0ce3fce4e04)
