### ISSUE TITLE
Vietnamese is not displayed in the settings

### ISSUE THREAD

**Issue by nguyenquanghoang** [DLXPlugins/pattern-wrangler#33]
All Strings are 100% translated https://translate.wordpress.org/locale/vi/default/wp-plugins/pattern-wrangler/
**but it doesn't show up in settings**

![pattern-wrangler-vietnam](https://github.com/user-attachments/assets/8ae7c2e6-98a3-460b-91dd-f0e6ba2b6a9e)

**Comment by ronalfy** [comment]
This is fixed in version 1.1.2.

**Comment by nguyenquanghoang** [comment]
Amazing, It has shown in Vietnamese. I will edit the translation to make it better. Thank you very much

**Comment by nguyenquanghoang** [comment]
> This is fixed in version 1.1.2.

Oh, it turns out that the default plugin turns on Caps Lock. With English, it looks nice, but with Vietnamese, the uppercase letters are very ugly. You should only put uppercase letters at the beginning of a line.

![2024-08-17_10-00-05](https://github.com/user-attachments/assets/14b92218-2891-400d-9181-bbabb80550fb)
